[default]
check-filename = true

[files]
extend-exclude = [
    "node_modules",
    "www",
    "*.yaml",
    ".vscode",
    "fastlane",
    "hooks",
    "*.gradle",
    "plugins",
    "platforms",
    "src/lang/ru-ru.json",
]

[default.extend-words]
# temporary thing to staisfy the linter
strech = "strech"
contaienr = "contaienr"
formate = "formate"
collapsable = "collapsable"
styl = "styl"
IZ = "IZ"
shft = "shft"
multline = "multline"
sav = "sav"
ist = "ist"
